site_name: Unofficial SAP BTP Service Overview
repo_url: https://github.com/SAP-samples/btp-setup-automator
nav:
  - Home: index.md
  - "Services drill down":
      - "PAYG accounts": service-overview.md
      - "Free Tier service plans": free-tier.md
      - "Supported environments": service-supportedEnvironments.md
theme:
  name: material
